apiVersion: v1
kind: ResourceQuota
metadata:
  name: tta-aiqa-object-budget
  namespace: tta-aiqa
spec:
  hard:
    count/configmaps: "50"
    count/persistentvolumeclaims: "10"
    count/pods: "30"
    count/secrets: "50"
    count/services: "30"
