apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/instance: ai-quality-risk-classifier-dev
      ai-quality/environment: dev
patches:
  - target:
      kind: InferenceService
      name: ai-quality-risk-classifier
    patch: |-
      - op: replace
        path: /spec/predictor/sklearn/storageUri
        value: pvc://ai-quality-models/risk-classifier/candidate-dev
      - op: add
        path: /metadata/annotations/ai-quality~1deployment-check
        value: manual-sync-required-before-deploy
