schema_version: 1
name: physionet-2012-canonical-v1
target: target
features:
- name: age
  dtype: float
  nullable: true
- name: age__missing
  dtype: boolean
  nullable: false
- name: gender
  dtype: category
  nullable: true
- name: gender__missing
  dtype: boolean
  nullable: false
- name: height
  dtype: float
  nullable: true
- name: height__missing
  dtype: boolean
  nullable: false
- name: icu_type
  dtype: category
  nullable: true
- name: icu_type__missing
  dtype: boolean
  nullable: false
- name: weight__min
  dtype: float
  nullable: true
- name: weight__max
  dtype: float
  nullable: true
- name: weight__mean
  dtype: float
  nullable: true
- name: weight__last
  dtype: float
  nullable: true
- name: weight__count
  dtype: float
  nullable: true
- name: weight__missing
  dtype: boolean
  nullable: false
- name: heart_rate__min
  dtype: float
  nullable: true
- name: heart_rate__max
  dtype: float
  nullable: true
- name: heart_rate__mean
  dtype: float
  nullable: true
- name: heart_rate__last
  dtype: float
  nullable: true
- name: heart_rate__count
  dtype: float
  nullable: true
- name: heart_rate__missing
  dtype: boolean
  nullable: false
- name: temperature__min
  dtype: float
  nullable: true
- name: temperature__max
  dtype: float
  nullable: true
- name: temperature__mean
  dtype: float
  nullable: true
- name: temperature__last
  dtype: float
  nullable: true
- name: temperature__count
  dtype: float
  nullable: true
- name: temperature__missing
  dtype: boolean
  nullable: false
- name: gcs__min
  dtype: float
  nullable: true
- name: gcs__max
  dtype: float
  nullable: true
- name: gcs__mean
  dtype: float
  nullable: true
- name: gcs__last
  dtype: float
  nullable: true
- name: gcs__count
  dtype: float
  nullable: true
- name: gcs__missing
  dtype: boolean
  nullable: false
- name: bun__min
  dtype: float
  nullable: true
- name: bun__max
  dtype: float
  nullable: true
- name: bun__mean
  dtype: float
  nullable: true
- name: bun__last
  dtype: float
  nullable: true
- name: bun__count
  dtype: float
  nullable: true
- name: bun__missing
  dtype: boolean
  nullable: false
- name: creatinine__min
  dtype: float
  nullable: true
- name: creatinine__max
  dtype: float
  nullable: true
- name: creatinine__mean
  dtype: float
  nullable: true
- name: creatinine__last
  dtype: float
  nullable: true
- name: creatinine__count
  dtype: float
  nullable: true
- name: creatinine__missing
  dtype: boolean
  nullable: false
- name: hematocrit__min
  dtype: float
  nullable: true
- name: hematocrit__max
  dtype: float
  nullable: true
- name: hematocrit__mean
  dtype: float
  nullable: true
- name: hematocrit__last
  dtype: float
  nullable: true
- name: hematocrit__count
  dtype: float
  nullable: true
- name: hematocrit__missing
  dtype: boolean
  nullable: false
- name: platelets__min
  dtype: float
  nullable: true
- name: platelets__max
  dtype: float
  nullable: true
- name: platelets__mean
  dtype: float
  nullable: true
- name: platelets__last
  dtype: float
  nullable: true
- name: platelets__count
  dtype: float
  nullable: true
- name: platelets__missing
  dtype: boolean
  nullable: false
- name: wbc__min
  dtype: float
  nullable: true
- name: wbc__max
  dtype: float
  nullable: true
- name: wbc__mean
  dtype: float
  nullable: true
- name: wbc__last
  dtype: float
  nullable: true
- name: wbc__count
  dtype: float
  nullable: true
- name: wbc__missing
  dtype: boolean
  nullable: false
- name: sodium__min
  dtype: float
  nullable: true
- name: sodium__max
  dtype: float
  nullable: true
- name: sodium__mean
  dtype: float
  nullable: true
- name: sodium__last
  dtype: float
  nullable: true
- name: sodium__count
  dtype: float
  nullable: true
- name: sodium__missing
  dtype: boolean
  nullable: false
- name: potassium__min
  dtype: float
  nullable: true
- name: potassium__max
  dtype: float
  nullable: true
- name: potassium__mean
  dtype: float
  nullable: true
- name: potassium__last
  dtype: float
  nullable: true
- name: potassium__count
  dtype: float
  nullable: true
- name: potassium__missing
  dtype: boolean
  nullable: false
- name: glucose__min
  dtype: float
  nullable: true
- name: glucose__max
  dtype: float
  nullable: true
- name: glucose__mean
  dtype: float
  nullable: true
- name: glucose__last
  dtype: float
  nullable: true
- name: glucose__count
  dtype: float
  nullable: true
- name: glucose__missing
  dtype: boolean
  nullable: false
- name: urine__min
  dtype: float
  nullable: true
- name: urine__max
  dtype: float
  nullable: true
- name: urine__mean
  dtype: float
  nullable: true
- name: urine__last
  dtype: float
  nullable: true
- name: urine__count
  dtype: float
  nullable: true
- name: urine__sum
  dtype: float
  nullable: true
- name: urine__missing
  dtype: boolean
  nullable: false
- name: non_invasive_systolic_bp__min
  dtype: float
  nullable: true
- name: non_invasive_systolic_bp__max
  dtype: float
  nullable: true
- name: non_invasive_systolic_bp__mean
  dtype: float
  nullable: true
- name: non_invasive_systolic_bp__last
  dtype: float
  nullable: true
- name: non_invasive_systolic_bp__count
  dtype: float
  nullable: true
- name: non_invasive_systolic_bp__missing
  dtype: boolean
  nullable: false
- name: non_invasive_diastolic_bp__min
  dtype: float
  nullable: true
- name: non_invasive_diastolic_bp__max
  dtype: float
  nullable: true
- name: non_invasive_diastolic_bp__mean
  dtype: float
  nullable: true
- name: non_invasive_diastolic_bp__last
  dtype: float
  nullable: true
- name: non_invasive_diastolic_bp__count
  dtype: float
  nullable: true
- name: non_invasive_diastolic_bp__missing
  dtype: boolean
  nullable: false
- name: non_invasive_map__min
  dtype: float
  nullable: true
- name: non_invasive_map__max
  dtype: float
  nullable: true
- name: non_invasive_map__mean
  dtype: float
  nullable: true
- name: non_invasive_map__last
  dtype: float
  nullable: true
- name: non_invasive_map__count
  dtype: float
  nullable: true
- name: non_invasive_map__missing
  dtype: boolean
  nullable: false
- name: ph__min
  dtype: float
  nullable: true
- name: ph__max
  dtype: float
  nullable: true
- name: ph__mean
  dtype: float
  nullable: true
- name: ph__last
  dtype: float
  nullable: true
- name: ph__count
  dtype: float
  nullable: true
- name: ph__missing
  dtype: boolean
  nullable: false
- name: pao2__min
  dtype: float
  nullable: true
- name: pao2__max
  dtype: float
  nullable: true
- name: pao2__mean
  dtype: float
  nullable: true
- name: pao2__last
  dtype: float
  nullable: true
- name: pao2__count
  dtype: float
  nullable: true
- name: pao2__missing
  dtype: boolean
  nullable: false
- name: fio2__min
  dtype: float
  nullable: true
- name: fio2__max
  dtype: float
  nullable: true
- name: fio2__mean
  dtype: float
  nullable: true
- name: fio2__last
  dtype: float
  nullable: true
- name: fio2__count
  dtype: float
  nullable: true
- name: fio2__missing
  dtype: boolean
  nullable: false
- name: mechanical_ventilation__max
  dtype: float
  nullable: true
- name: mechanical_ventilation__last
  dtype: float
  nullable: true
- name: mechanical_ventilation__count
  dtype: float
  nullable: true
- name: mechanical_ventilation__missing
  dtype: boolean
  nullable: false
- name: lactate__min
  dtype: float
  nullable: true
- name: lactate__max
  dtype: float
  nullable: true
- name: lactate__mean
  dtype: float
  nullable: true
- name: lactate__last
  dtype: float
  nullable: true
- name: lactate__count
  dtype: float
  nullable: true
- name: lactate__missing
  dtype: boolean
  nullable: false
