apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - alloy-rbac.yaml
  - alloy.yaml
configMapGenerator:
  - name: alloy-config
    namespace: tta-aiqa
    files:
      - config.alloy=config/config.alloy
generatorOptions:
  disableNameSuffixHash: true
